### ISSUE TITLE
 Argument 1 passed to Laravel\Passport\Bridge\UserRepository::__construct() must be an instance of Illuminate\Hashing\HashManager,

### ISSUE THREAD

**Issue by audetcameron** [matriphe/laravel-md5-hash#4]
When you change the default settings , this error gets thrown on a php artisan route:list

   Symfony\Component\Debug\Exception\FatalThrowableError  : Argument 1 passed to Laravel\Passport\Bridge\UserRepository::__construct() must be an instance of Illuminate\Hashing\HashManager, instance of App\Classes\Md5Hash given

**Comment by matriphe** [comment]
Fixed in #10
