### ISSUE TITLE
Class Matriphe\Md5Hash\Md5Hash contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Illuminate\Contracts\Hashing\Hasher::info) 

### ISSUE THREAD

**Issue by dialmedu** [matriphe/laravel-md5-hash#6]
"name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.1.3",
        "cmgmyr/messenger": "^2.19",
        "fideloper/proxy": "^4.0",
        "laravel/framework": "5.8.*",
        "laravel/tinker": "^1.0",
        "matriphe/laravel-md5-hash": "^1.0"
    },

don't implements function `info()` of Hasher

**Comment by dialmedu** [comment]
Solved clone repo branch master, please update for version.

add DEV-MASTER to be able to work
` "matriphe/laravel-md5-hash": "dev-master" `

**Comment by ohryan** [comment]
@dialmedu there is no `dev-master` branch!
